### ISSUE TITLE
Allow import-from-derivation so Haskell projects can build with this action

### ISSUE THREAD

**Issue by ParetoOptimalDev** [nixbuild/nixbuild-action#42]
I think that two things have to happen:

- allow putting `allow-import-derivation` as a config option
- allow specifying number of builders to 1 for IFD [here](https://github.com/nixbuild/nixbuild-action/blob/master/nixbuild-action.sh#L157)

**Comment by w4** [comment]
I've been looking into this myself, turns out you can already set IFD as a config option:

```
jobs:
  build:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v17
    secrets:
      nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
    with:
      nix_conf: |
        allow-import-from-derivation = true
```
